package badger

// This file handles final AI response parsing, text-only responses, write-plan
// application, and apply confirmation output for headless mode.

import (
	"bufio"
	"fmt"
	"io"
	"strings"

	"github.com/PVRLabs/aibadger/internal/workflow"
	"github.com/PVRLabs/aibadger/internal/writer"
)

func handleFinalResponse(w io.Writer, reader *bufio.Reader, session *workflow.Session, opts HeadlessOptions) bool {
	promptTwoKind := workflow.PromptTwoKind(opts.Focus)
	if opts.InputPath == "" {
		fmt.Fprintln(w, "\nNext steps:")
		fmt.Fprintf(w, "1. Paste %s into your AI chat.\n", promptTwoKind)
		fmt.Fprintln(w, "2. Copy the final response generated by AI.")
		fmt.Fprintln(w, "3. Paste it below and type 'DONE' on a new line to finish.")
		fmt.Fprint(w, "\n> ")
	}
	finalCode := readInput(w, opts)

	final := session.ParseFinalResponse(finalCode)
	result := final.Parse
	updates := result.Updates
	if isWritePlanStep(opts.Step) {
		printHeadlessResponsePlan(w, finalCode, result)
		return true
	}
	if final.HasErrors {
		for _, err := range result.Errors {
			fmt.Fprintf(w, "Parse error: %v\n", err)
		}
		return false
	}

	if !final.HasUpdates {
		printTextResponse(w, result.Text)
		return false
	}

	printMixedResponseNotes(w, result.Text)
	applyUpdates(w, reader, session, updates)
	return false
}

func applyUpdates(w io.Writer, reader *bufio.Reader, session *workflow.Session, updates []writer.FileUpdate) {
	fmt.Fprintf(w, "\n[✓] Parsed %d file operations.\n", len(updates))
	fmt.Fprintln(w, "\nAbout to apply changes to disk:")
	for _, up := range updates {
		kind := "write"
		if up.Kind == writer.UpdateKindDelete {
			kind = "delete"
		}
		fmt.Fprintf(w, "  [%s] %s\n", kind, up.Path)
	}
	fmt.Fprint(w, "\nApply changes? (y/N): ")
	if !confirm(reader) {
		fmt.Fprintln(w, "Cancelled.")
		return
	}

	for _, up := range updates {
		if err := session.ApplyWrite(up); err != nil {
			fmt.Fprintf(w, "Error applying %s: %v\n", up.Path, err)
			continue
		}
		switch up.Kind {
		case writer.UpdateKindDelete:
			fmt.Fprintf(w, "[✓] Deleted %s\n", up.Path)
		default:
			fmt.Fprintf(w, "[✓] Wrote %s\n", up.Path)
		}
	}
	fmt.Fprintln(w, "\n[✓] Changes applied.")
	fmt.Fprintln(w, "\n(Hint: You can now ask follow-up questions or request the next change. The AI in your chat window already knows the full history.)")
}

func printTextResponse(w io.Writer, finalCode string) {
	if strings.TrimSpace(finalCode) != "" {
		printAIBanner(w, "\n[i] No file updates found. AI provided a textual response.", finalCode)
		return
	}
	fmt.Fprintln(w, "\n[i] Empty response received.")
}

func printMixedResponseNotes(w io.Writer, text string) {
	if strings.TrimSpace(text) == "" {
		return
	}
	printAIBanner(w, "\n[i] AI included notes alongside file updates.", text)
}

func printAIBanner(w io.Writer, preamble, text string) {
	fmt.Fprintln(w, preamble)
	fmt.Fprintln(w, "\nAI Analysis / Explanation:")
	fmt.Fprintln(w, "---------------------------")
	fmt.Fprintln(w, text)
	fmt.Fprintln(w, "---------------------------")
}
